apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fixmate-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - fixmate
  selector:
    matchLabels:
      app: fixmate-backend
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
