apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: fixmate
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres.fixmate.svc.cluster.local:5432/fixmatedb" this for k8s
#  SPRING_DATASOURCE_URL: "jdbc:postgresql://127.0.0.1:5432/fixmate?sslmode=disable" #CloudSQL
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_SHOW_SQL: "true"

  FLYWAY_LOCATIONS: "classpath:db/migration"
  FLYWAY_BASELINE_ON_MIGRATE: "true"

  SERVER_PORT: "8081"

  GCP_BUCKET_NAME: "fixmate-files-490017"
  GCP_PROJECT_ID: "fixmate-490017"


