CREATE TABLE email_change_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    otp VARCHAR(6) NOT NULL,
    new_email VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,

    PRIMARY KEY (id),

    CONSTRAINT uk_email_change_token_user UNIQUE (user_id),

    CONSTRAINT fk_email_change_token_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);